---
title: "Preliminary Analysis"
output: html_document
date: "2025-12-04"
---
##Setups
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = FALSE)
library(ggplot2)
library(dplyr)
library(tidyverse)
library(foreign)
library(lavaan)
library(lme4)
library("dagitty")
library("semPower")
library("semPlot")
library(lubridate)
library(hms)
EMA_final <- readRDS("EMA_final.rds")
glimpse(EMA_final)
```

## Sample size and specific sample sizes.
```{r}
#Counting final sample size
EMA_final %>%
  summarise(n = n_distinct(ID)) 
#Breakdown of group membership
EMA_final %>%
  group_by(Group) %>%
  summarise(n = n_distinct(ID))
#Prompts completed by each ppt
EMA_final %>%
  group_by(ID) %>%
  summarise(n_prompts = n()) %>%
  ungroup()
```

## Descriptives of SI
```{r}
#Proportion of prompts containing each type of SI
EMA_final %>%
  summarise(
    prop_any = mean(SI_any == 1, na.rm = TRUE),
    prop_pass = mean(passiveSI == 1, na.rm = TRUE),
    prop_act = mean(activeSI == 1, na.rm = TRUE),
    prop_SMI = mean(SMI == 1, na.rm = TRUE)
  )
```

## Descriptives of events
```{r}
#Proportion of prompts containing events
EMA_final %>%
  summarise(
    prop_stress = mean(stress_any == 1, na.rm = TRUE),
    prop_stressint1 = mean(stress_int == 1, na.rm = TRUE),
    prop_stressint2 = mean(stress_int == 2, na.rm = TRUE),
    prop_pos = mean(pos_any == 1, na.rm = TRUE),
    prop_posint1 = mean(pos_int == 1, na.rm = TRUE),
    prop_posint2 = mean(pos_int == 2, na.rm = TRUE)
  )
#Measuring collinearity of stress and positivity
#First making a table with the two events
tab_events <- with(EMA_final, table(stress_any, pos_any))
tab_events
prop.table(tab_events)           # proportions of all prompts
prop.table(tab_events, 1)        
prop.table(tab_events, 2)        
#Now using the table to measure how % stress so-occurred with pos and vice versa
n_both   <- tab_events["1", "1"]
n_total  <- sum(tab_events)
both <- n_both / n_total 

n_stress <- sum(tab_events["1", ])
stress_with_pos <- n_both / n_stress

n_pos    <- sum(tab_events[ , "1"])
pos_with_stress <- n_both / n_pos


```

## Descriptives of affect
```{r}
#glimpse at affect
summary(EMA_final$current_affect)
#affect breakdown by SI
EMA_final %>%
  group_by(SI_any) %>%
  summarise(
    mean_affect = mean(current_affect, na.rm = TRUE),
    sd_affect = sd(current_affect, na.rm = TRUE)
  )
#Okay, ppts had a general negative mood when SI
#Affects in stress - negative event-related affect
EMA_final %>%
  group_by(stress_int) %>%
  summarise(
    nNA = n(),
    mean_NA = mean(current_affect, na.rm = TRUE),
    sd_NA = sd(current_affect, na.rm = TRUE)
  ) %>%
  ungroup()
#Affect in pleasantness - positive event-related affect
EMA_final %>%
  group_by(pos_int) %>%
  summarise(
    nPA = n(),
    mean_PA = mean(current_affect, na.rm = TRUE),
    sd_PA = sd(current_affect, na.rm = TRUE)
  ) %>%
  ungroup()
#Hmmm...even though we have collinearity, but ppts still seem more happy in positive events and less happy in negative events.
```
##Check missingness
```{r}

sapply(EMA_final, function(x) mean(is.na(x)))

```

##Computing the (T-1) variables, disabling overnight lag.
```{r}
#Mark every first prompt of a day
EMA_mplus <- EMA_final %>%
  arrange(ID, survey_dtime) %>%
  group_by(ID) %>%
  mutate(
    day = as.Date(survey_dtime),
    new_d = is.na(lag(day)) | day != lag(day)
  ) %>%
  ungroup()
#Create a new variable for affect(T-1) and SI(T-1), which will be input into Mplus as predictors. Disabling every first prompt of the day shall avoid overnight lag.
EMA_mplus <- EMA_mplus %>%
  mutate(
    affect_T_1 = if_else(new_d, NA_real_, lag(current_affect)),
    SI_T_1 = if_else(new_d, NA_real_, lag(SI_any))
  )
```

##Computing post-event affect(T).
```{r}
#Filtering out post-event affect. These will be outcome variables for each event type.
EMA_mplus <- EMA_mplus %>%
  mutate(
    affect_post_stress = if_else(post_stress_affect == 1L,
                                 current_affect,
                                 NA_real_),
    affect_post_pos = if_else(post_pos_affect == 1L,
                              current_affect,
                              NA_real_)
  )
glimpse(EMA_mplus)
```

##Counting valid post-event affects we have - valid pairs for DSEM per ppt
```{r}
#Counting valid post-stress prompts
EMA_mplus %>%
  summarise(
  n_post_stress = sum(!is.na(post_stress_affect)))
EMA_mplus %>%
  group_by(ID) %>%
  count(!is.na(post_stress_affect))

#counting valid post-positive prompts
EMA_mplus %>%
  summarise(
    n_post_pos = sum(!is.na(post_pos_affect))
  )
EMA_mplus %>%
  group_by(ID) %>%
  count(!is.na(post_pos_affect))

```


##Making a tibble ready to be put into Mplus for analysis of Aim 1 and 2.
```{r}
#Selecting variables I want to carry.
EMA_mplus_aim12 <- EMA_mplus %>%
  ungroup() %>%
  select(ID, current_affect, passiveSI, activeSI, SMI, SI_any, stress_int, pos_any, stress_any, pos_int, affect_T_1, SI_T_1, affect_post_stress, affect_post_pos)
glimpse(EMA_mplus_aim12)
#
write.table(
  EMA_mplus_aim12,
  "EMA_mplus12.dat",
  row.names = FALSE,
  col.names = FALSE,
  na = "-9999")
```

